package com.example.quintrixgroupproject.mwapi

class DictionaryResponse2 : ArrayList<DictionaryResponse2Item>()
//autogenerated using another tool
//it also finds that sseq must by Any for some reason.
//Seems like this is actually an issue with the JSON response from the API
//but that is out of our control

data class DictionaryResponse2Item(
    val cxs: List<Cx>,
    val date: String,
    val def: List<Def>,
    val fl: String,
    val hom: Int,
    val hwi: Hwi,
    val ins: List<In>,
    val meta: Meta,
    val shortdef: List<String>,
    val uros: List<Uro>,
    val vrs: List<VrX>
)

data class Cx(
    val cxl: String,
    val cxtis: List<Cxti>
)

data class Def(
    val sseq: List<List<List<Any>>>,
    val vd: String
)

data class Hwi(
    val hw: String,
    val prs: List<Pr>
)

data class In(
    val `if`: String,
    val il: String
)

data class Meta(
    val id: String,
    val offensive: Boolean,
    val section: String,
    val sort: String,
    val src: String,
    val stems: List<String>,
    val uuid: String
)

data class Uro(
    val fl: String,
    val prs: List<PrX>,
    val ure: String,
    val utxt: List<List<Any>>,
    val vrs: List<Vr>
)

data class VrX(
    val va: String,
    val vl: String
)

data class Cxti(
    val cxt: String
)

data class Pr(
    val mw: String,
    val sound: Sound
)

data class Sound(
    val audio: String,
    val ref: String,
    val stat: String
)

data class PrX(
    val mw: String,
    val sound: SoundX
)

data class Vr(
    val va: String,
    val vl: String
)

data class SoundX(
    val audio: String,
    val ref: String,
    val stat: String
)